// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAlert: typeof import('./../components/App/AppAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../components/App/TheHeader.vue')['default']
    TheSidebar: typeof import('./../components/App/TheSidebar.vue')['default']
  }
}
