// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    LayoutHeader: typeof import('./../components/Layout/Header.vue')['default']
    LayoutSidebar: typeof import('./../components/Layout/Sidebar.vue')['default']
    LayoutTheHeader: typeof import('./../components/Layout/TheHeader.vue')['default']
    LayoutTheSidebar: typeof import('./../components/Layout/TheSidebar.vue')['default']
  }
}

export { }
